
REQUEST_PARSER_DEBUG = False
RESOLVER_DEBUG = False
ITEROR_DEBUG = False
CACHE_DEBUG = False
RESPOND_BUILDER_DEBUG = False


# request parser param
MAXIMUM_POINTER_JUMP = 20
MAXIMUM_LABEL_LENGTH = 63
FULL_NAME_LENGTH = 255


# resolver params
MAX_ATTEMPTS = 50
MAX_REFERRALS = 10
MAX_CNAME_DEPTH = 10
